env: stage
ocp_host: https://api.pipelines-stage.0ce8.p1.openshiftapps.com:6443
branch: "{{ env }}"
operator_pipeline_webhook_secret: ../../vaults/common/github-webhook-secret-preprod.txt

# how many of newest pipelineruns should be presrved on cleanup?
preserve_after_cleanup: 5
