---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-cert-project-related-data
spec:
  params:
    - name: cert_project_id
      description: Identifier of certification project from Red Hat Connect
    - name: pyxis_cert_path
      default: ""
      description: Path to Pyxis certificates. Valid only when internal Pyxis is used.
    - name: pyxis_key_path
      default: ""
    - name: pyxis_url
      default: https://pyxis.engineering.redhat.com
  results:
    - name: isv_pid
      description: isv_pid of the certification project from Red Hat Connect
    - name: repo_name
      description: Repository name assigned to certification project from Red Hat Connect
    - name: dist_method
      description: Distribution method of the certification project- either certified or marketplace
    - name: org_id
      description: Unique identifier of the organization in Red Hat Connect
    - name: contacts
      description: List of accounts with permissions allowing operator submission
    - name: certification_status
      description: Certification status of the cert Project
  workspaces:
    - name: pyxis-ssl-credentials
      optional: true
  steps:
    - name: get-cert-project-related-data
      image: quay.io/redhat-isv/operator-pipelines-images:latest
      env:
        - name: PYXIS_CERT_PATH
          value: $(params.pyxis_cert_path)
        - name: PYXIS_KEY_PATH
          value: $(params.pyxis_key_path)
      script: |
        #! /usr/bin/env bash
        set -xe -o pipefail

        get-cert-project-related-data \
          --pyxis-url $(params.pyxis_url) \
          --cert-project-id $(params.cert_project_id)

        CERTIFICATION_STATUS=$(cat cert_project | jq '.certification_status'| tr -d '"')
        if [ $CERTIFICATION_STATUS == "Started" ]; then
          echo -n "In Progress" | tee $(results.certification_status.path)
        fi

        # `grep .` ensures, that pipe fail if jq returns no results
        cat cert_project | jq '.container.isv_pid' | tr -d '"' | grep . | tee $(results.isv_pid.path)
        cat cert_project | jq '.container.repository_name' | tr -d '"' | grep . | tee $(results.repo_name.path)
        cat cert_project | jq '.container.distribution_method' | tr -d '"' |  grep . | tee $(results.dist_method.path)
        cat cert_project | jq '.org_id' | tr -d '"' |  tr -d '"' | grep . | tee $(results.org_id.path)
        cat cert_project | jq '.contacts[].email_address' | tr '\n' ' ' | tr -d '"' | grep . | tee $(results.contacts.path)
