---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ocp-environment-cleanup
spec:
  params:
    - name: package_name
    - name: index_image
    - name: preflight_results_exists
      default: "false"
  workspaces:
    - name: source
  steps:
    - name: uninstall-operator
      image: registry.access.redhat.com/ubi8-minimal@sha256:54ef2173bba7384dc7609e8affbae1c36f8a3ec137cacc0866116d65dd4b9afe
      workingDir: $(workspaces.source.path)
      script: |
        #! /usr/bin/env bash
        PREFLIGHT_RESULTS_EXISTS="$(params.preflight_results_exists)"
        if [ $PREFLIGHT_RESULTS_EXISTS == "true" ]; then
          echo "Preflight results already exists- skipping"
          exit 0
        fi

        echo "Uninstalling operator from a cluster: $(params.package_name)"

    - name: remove-index
      image: registry.access.redhat.com/ubi8-minimal@sha256:54ef2173bba7384dc7609e8affbae1c36f8a3ec137cacc0866116d65dd4b9afe
      workingDir: $(workspaces.source.path)
      script: |
        #! /usr/bin/env bash
        PREFLIGHT_RESULTS_EXISTS="$(params.preflight_results_exists)"
        if [ $PREFLIGHT_RESULTS_EXISTS == "true" ]; then
          echo "Preflight results already exists- skipping"
          exit 0
        fi

        echo "Removing custom index from ocp: $(params.index_image)"
