---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: publish-bundle
spec:
  params:
    - name: cert_project_id
      description: ID of the bundle Certification Project (as in bundle ci.yaml)
    - name: container_digest
      description: imagestream container_digest
    - name: bundle_versions
      description: All known supported OCP indices
  results:
    - name: status
      description: Indicates a status of publishing a bundle to an index
  steps:
    - name: publish-bundle
      image: registry.access.redhat.com/ubi8-minimal@sha256:54ef2173bba7384dc7609e8affbae1c36f8a3ec137cacc0866116d65dd4b9afe
      script: |
        #! /usr/bin/env bash
        echo "Starting bundle publish process"
        echo "updating GitHub status to pending"
        echo "Calling the IIB"
        echo "Got result- updating GitHub status"

        echo "success" | tee "$(results.status.path)"
