---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-support-link-for-pr
spec:
  params:
    - name: env
      description: Enviroment. One of [dev, qa, stage, production]
    - name: type
      description: Connect case type.
      default: "CERT"
    - name: source
      description: Connect case source.
      default: "tekton"
    - name: cert_project_id
      description: Pyxis certification project id.
    - name: cert_project_type
      description: Connect cert project type. Should be Operator Bundle Image for operator pipelines.
      default: "Operator Bundle Image"
    - name: pull_request_url
      default: ""
  results:
    - name: comment
  steps:
    - name: create-support-link-for-pr
      image: quay.io/redhat-isv/operator-pipelines-images
      script: |
        #! /usr/bin/env bash
        set -e

        LINK_ENV="$(params.env)"
        # url parameters
        LINK_TYPE=$(printf %s "$(params.type)")
        LINK_SOURCE=$(printf %s "$(params.source)")
        CERT_PROJECT_ID=$(printf %s "$(params.cert_project_id)")
        CERT_PROJECT_TYPE=$(printf %s "$(params.cert_project_type)")
        PULL_REUQEST_URL=$(printf %s "$(params.pull_request_url)")

        echo "Follow this link if you wish to open a support case:"
        echo "https://$URL_ENV.redhat.com/support/technology-partner/#/case/new?type=$LINK_TYPE&source=$LINK_SOURCE&cert_project_id=$CERT_PROJECT_ID&cert_project_type=$CERT_PROJECT_TYPE&pull_request_url=$PULL_REUQEST_URL" | tee $(results.comment.path)
