---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-cert-project-status
spec:
  params:
    - name: cert_project_id
      description: Identifier of certification project from Red Hat Connect
    - name: pyxis_cert_path
      default: ""
      description: Path to Pyxis certificates. Valid only when internal Pyxis is used.
    - name: pyxis_key_path
      default: ""
    - name: pyxis_url
      default: https://pyxis.engineering.redhat.com
    - name: certification_status
      description: Certification status of the cert Project
  workspaces:
    - name: pyxis-ssl-credentials
      optional: true
  steps:
    - name: update-cert-project-status
      image: quay.io/redhat-isv/operator-pipelines-images:latest
      env:
        - name: PYXIS_CERT_PATH
          value: $(params.pyxis_cert_path)
        - name: PYXIS_KEY_PATH
          value: $(params.pyxis_key_path)
        - name: PYXIS_URL
          value: $(params.pyxis_url)
        - name: CERT_PROJECT_ID
          value: $(params.cert_project_id)
        - name: CERTIFICATION_STATUS
          value: $(params.certification_status)
      script: |
        #! /usr/bin/env bash
        set -xe

        update-cert-project-status \
          --pyxis-url $PYXIS_URL \
          --cert-project-id $CERT_PROJECT_ID \
          --certification-status "$CERTIFICATION_STATUS"

        echo "Updating the Certification Project status to $CERTIFICATION_STATUS"
