---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-cert-project-status
spec:
  params:
    - name: pipeline_image
    - name: new_certification_status
      description: New Certification status of the cert Project
    - name: cert_project_id
      description: Identifier of certification project from Red Hat Connect
    - name: pyxis_cert_path
      default: ""
      description: Path to Pyxis certificates. Valid only when internal Pyxis is used.
    - name: pyxis_key_path
      default: ""
    - name: pyxis_url
      default: https://pyxis.engineering.redhat.com
    - name: current_certification_status
      description: Current Certification status of the cert Project
  workspaces:
    - name: pyxis-ssl-credentials
      optional: true
  steps:
    - name: update-cert-project-status
      image: "$(params.pipeline_image)"
      env:
        - name: PYXIS_CERT_PATH
          value: $(params.pyxis_cert_path)
        - name: PYXIS_KEY_PATH
          value: $(params.pyxis_key_path)
        - name: PYXIS_URL
          value: $(params.pyxis_url)
        - name: CERT_PROJECT_ID
          value: $(params.cert_project_id)
        - name: CURRENT_CERTIFICATION_STATUS
          value: $(params.current_certification_status)
        - name: NEW_CERTIFICATION_STATUS
          value: $(params.new_certification_status)
      script: |
        #! /usr/bin/env bash
        set -xe

        if [ "$CURRENT_CERTIFICATION_STATUS" != "$NEW_CERTIFICATION_STATUS" ]; then
          echo "Updating the Certification Project status to $NEW_CERTIFICATION_STATUS."
          update-cert-project-status \
            --pyxis-url $PYXIS_URL \
            --cert-project-id $CERT_PROJECT_ID \
            --certification-status "$NEW_CERTIFICATION_STATUS"

          echo "The Certification Project status is successfully updated to $NEW_CERTIFICATION_STATUS state."
          exit 0
        fi

        echo "The certification project is currently in $CURRENT_CERTIFICATION_STATUS state."
