---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: verify-ci-results
spec:
  params:
    - name: preflight_results
    - name: preflight_min_version
    - name: ci_min_version
  results:
    - name: test_result
      description: Result from the preflight test.
  workspaces:
    - name: results
  steps:
    - name: verify-ci-results
      image: quay.io/redhat-isv/operator-pipelines-images:latest
      workingDir: $(workspaces.results.path)
      env:
        - name: PREFLIGHT_RESULTS
          value: $(params.preflight_results)
      script: |
        #! /usr/bin/env bash
        set -xe -o pipefail

        # Did the tests pass?
        # In case of failure- comment on the PR with tailored support link
        CHECK_RESULTS=$(echo $PREFLIGHT_RESULTS | jq '.passed' | tr -d '"' | grep .)
        if [ $CHECK_RESULTS = "false" ]; then
          echo "failure" | tee $(results.test_result.path)
          exit 0
        fi

        echo "success" | tee $(results.test_result.path)
