---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: verify-ci-results
spec:
  params:
    - name: preflight_results
    - name: preflight_min_version
    - name: ci_min_version
  results:
    - name: test_result
      description: Result from the preflight test.
  workspaces:
    - name: results
  steps:
    - name: verify-ci-results
      image: registry.access.redhat.com/ubi8-minimal
      workingDir: $(workspaces.results.path)
      script: |
        #! /usr/bin/env bash

        # did preflight/ CI have the latest version?
        PREFLIGHT_VERSION=$(cat PREFLIGHT_RESULTS | jq '.test_library.version' | grep .)
        if [$PREFLIGHT_VERSION < $(params.preflight_min_version)]; then
          echo "preflight is having an outdated version"
          exit 1
        fi

        # TODO replace with real value
        echo "success" | tee $(results.test_result.path)
