---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: verify-changed-directories
spec:
  params:
    - name: image_tag
    - name: operator_name
    - name: bundle_version
    - name: pr_head_label
    - name: git_repo_url
    - name: base_branch
      default: main
  steps:
    - name: verify-changed-directories
      image: quay.io/redhat-isv/operator-pipelines-images:latest
      script: |
        #! /usr/bin/env bash
        set -xe

        verify-changed-dirs \
          --operator-name="$(params.operator_name)" \
          --bundle-version="$(params.bundle_version)" \
          --pr-head-label="$(params.pr_head_label)" \
          --git-repo-url="$(params.git_repo_url)" \
          --base-branch="$(params.base_branch)" \
          --verbose
