---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: verify-ci-results
spec:
  params:
    - name: preflight_min_version
    - name: ci_min_version
  results:
    - name: test_result
      description: Result from the preflight test.
  workspaces:
    - name: results
  steps:
    - name: verify-ci-results
      image: registry.access.redhat.com/ubi8-minimal@sha256:54ef2173bba7384dc7609e8affbae1c36f8a3ec137cacc0866116d65dd4b9afe
      workingDir: $(workspaces.results.path)
      script: |
        #! /usr/bin/env bash
        # Did the tests pass?
        # did preflight/ CI have the latest version?
        # If results exists, store them in the workspace
        # In case of failure- comment on the PR with tailored support link

        # TODO replace with real value
        echo "success" | tee $(results.test_result.path)
