---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: verify-ci-results
spec:
  params:
    - name: preflight_results
    - name: preflight_min_version
    - name: ci_min_version
  results:
    - name: test_result
      description: Result from the preflight test.
  workspaces:
    - name: results
  steps:
    - name: verify-ci-results
      image: registry.access.redhat.com/ubi8-minimal
      workingDir: $(workspaces.results.path)
      env:
        - name: PREFLIGHT_MIN_VERSION
          value: $(params.preflight_min_version)
        - name: PREFLIGHT_RESULTS
          value: $(params.preflight_results)
      script: |
        #! /usr/bin/env bash
        set -o pipefail

        # did preflight/ CI have the latest version?
        PREFLIGHT_VERSION=$(cat $PREFLIGHT_RESULTS | jq '.test_library.version' | grep .)
        if [ "$(printf '%s\n' "$PREFLIGHT_MIN_VERSION" "$PREFLIGHT_VERSION" | sort -V | head -n1)" = "$PREFLIGHT_MIN_VERSION" ]; then
          echo "Preflight version satisfies the minimun requirement of version"
        else
          echo "Preflight is having an outdated version $PREFLIGHT_VERSION"
          echo "Preflight version requires version $PREFLIGHT_MIN_VERSION or higher."
          echo "failure" | tee $(results.test_result.path)
          exit 1
        fi

        # TODO replace with real value
        echo "success" | tee $(results.test_result.path)
